### ISSUE TITLE
Como obtener el unixtime con la librería

### ISSUE THREAD

**Issue by lgaticaq** [geekfactory/RTCLib#1]

**Comment by geekfactory** [comment]
Hola.

Utilizando la librerìa TimeLib en conjunto con RTCLib:

https://github.com/geekfactory/TimeLib
https://github.com/geekfactory/RTCLib

1) Usar el metodo RTC.get() para obtener el tiempo del RTC en formato timestamp directamente.

time_t stamp = RTC.get();

2) Obtener el tiempo desde el RTC en una estructura time_t y luego pasarlo a la funcion time_make() para que lo convierta a timestamp (Esta forma parte de la librería TimeLib). Esto lo hace en un solo paso el metodo mencionado anteriormente. 

struct tm timedate;
RTC.read(timedate);
time_t time_make(&timedate);

3) Internamente la librería TimeLib funciona como un "RTC por software" que lleva la cuenta en segundos (Tiempo Unix). Para configurar y obtener el valor actual del timestamp que va contando el CPU usamos:

// Primero poner a tiempo la libreria time, usando el RTC como referencia
time_set(RTC.get());
// Despues podemos consultar el conteo en tiempo que lleva el CPU
time_t stamp = time_get();

Espero que te sirva, saludos.

**Comment by lgaticaq** [comment]
Muchas gracias

**Comment by geekfactory** [comment]
Espero que te sirva, saludos.
